name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Build win64 extract
        run: GOARCH=amd64 GOOS=windows go build -v ./cmd/extract
      - name: Build win64 build
        run: GOARCH=amd64 GOOS=windows go build -v ./cmd/build
      - name: Upload win64 binary distro artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-win64
          path: |
            extract.exe
            build.exe
            README.md